/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import controler.ControlerFactory;
import controler.ControlerJogo;
import controler.IControllerJogo;
import javax.swing.JOptionPane;
import model.Jogador;
import model.Palavra;
import persistencia.PersistenciaFactory;

/**
 *
 * @author Andre
 */
public class TelaJogo extends javax.swing.JFrame {
    
    /**
     * Creates new form TelaJogo
     */
    private Jogador jogador=null;
    private Palavra  palavra =null;
    private char[] vetorPalavra;
    private char[] vetorMascara;
    private int erros;
    TelaJogo(Jogador jogador) {
        this.jogador=jogador;
        initComponents();
        disporPalavra();
    }
    private void disporPalavra(){
        IControllerJogo cj = ControlerFactory.obterControlerJogo();
        palavra=cj.obterPalavra();
        lbDica.setText(palavra.getDica());
        int tamanho = palavra.getPalavra().length();
        vetorPalavra = new char[tamanho];
        vetorMascara = new char[tamanho];
        for(int i =0; i < tamanho; i++){
            vetorMascara[i] = '*';
            vetorPalavra[i] = palavra.getPalavra().charAt(i);
        }
        lbPalavra.setText(new String(vetorMascara));
        erros = 0;
        lbErro.setText(erros + "/6");
        this.lbLetrasUsadas.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfLetra = new javax.swing.JTextField();
        btChutar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbDica = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbLetrasUsadas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbErro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbPalavra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Forca");

        jLabel2.setText("Digite uma letra:");

        btChutar.setText("Chutar");
        btChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChutarActionPerformed(evt);
            }
        });

        jLabel3.setText("Dica:");

        lbDica.setText("Dica aqui<-");

        jLabel5.setText("Letras usadas:");

        jLabel7.setText("Erros cometidos:");

        lbErro.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Palavra:");

        lbPalavra.setText("_ _ _ _ _ _");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lbDica))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLetrasUsadas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btChutar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbErro)
                            .addComponent(lbPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbDica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPalavra))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbErro))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbLetrasUsadas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btChutar))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btChutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChutarActionPerformed
        // TODO add your handling code here:
        char letra = tfLetra.getText().charAt(0);
        int tamanho = vetorPalavra.length;
        boolean contem = false;
        for(int i = 0; i<tamanho; i++){
            if(vetorPalavra[i] == letra){
                vetorMascara[i]=letra;
                contem = true;
            }            
        }
        if(!contem)
            erros++;
        lbErro.setText(erros+"/6");
        lbLetrasUsadas.setText(lbLetrasUsadas.getText() +letra+" ");
        lbPalavra.setText(new String(vetorMascara));
        tfLetra.setText("");
        verificarTermino();
        
    }//GEN-LAST:event_btChutarActionPerformed
    private void verificarTermino(){
        if(erros>=6){
            JOptionPane.showMessageDialog(rootPane,"Voce perdeu :(");
            disporPalavra();
            
        }
     String verificarPalavra = new String(vetorMascara);
     if(verificarPalavra.equals(palavra.getPalavra())){
         JOptionPane.showMessageDialog(rootPane,"Parabens,voce ganhou!");
         disporPalavra();
     }
    }
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbDica;
    private javax.swing.JLabel lbErro;
    private javax.swing.JLabel lbLetrasUsadas;
    private javax.swing.JLabel lbPalavra;
    private javax.swing.JTextField tfLetra;
    // End of variables declaration//GEN-END:variables
}
